### PR TITLE
Use dive instead of findit to prevent issue

### PR DESCRIPTION
**Pull request by pvorb**
There is an issue in [findit](https://github.com/substack/node-findit)/[seq](https://github.com/substack/node-seq) that causes nide to crash when loading a big project:
- https://github.com/substack/node-findit/issues/2
- https://github.com/substack/node-seq/issues/17

[massimiliano-giroldi](https://github.com/massimiliano-giroldi) asked me, if [dive](https://github.com/pvorb/node-dive) could do the job. I looked at the code of seq and assumed the error got something to do with the chaining of seq.

So I patched nide. Now
- it uses [dive](https://github.com/pvorb/node-dive)
- it's faster
- [issue](https://github.com/substack/node-seq/issues/17) does not occur anymore

Feel free to test it.

### CODE REVIEW

**Comment by coreh** [comment]
Wow man, thank you so much for this!

I tried it on a directory structure with thousands of files and hundreds of subdirectories, and the issue seems to be gone. Project loading also feels so much faster now. Thanks to you and @massimiliano-giroldi.

**Comment by pvorb** [comment]
NP. That was fun ;).

Cool project, by the way!

**Comment by max-giro** [comment]
nide & dive rocks together!

P.S.:
I think now there is a .nide dir (5.5MB) installed with the module (needs cleaning?).

**Comment by coreh** [comment]
oops. But that's strange. It's fixed now, but if you look at my .npmignore
file, .nide _is_ there.

-- Marco Aurlio

**Comment by max-giro** [comment]
Reinstalei de novo e agora está mesmo sem a 'bagagem' toda : )

**Pull request merged**
